site_name: Rust Package building example
site_url: https://rincewindwizzard.github.io/rust-package-building-example/
repo_url: https://github.com/RincewindWizzard/rust-package-building-example.git
edit_uri: ./edit/main/docs/

theme:
  name: readthedocs
  language: de

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md